pin scipy to 1.7.3
This is due to an error arising from the ABI of libstc++ at runtime wrt to
the version at build time, leading to
errors like https://discord.com/channels/929016277266219038/930484078271160361/1021436273233240156
ImportError: /usr/share/miniconda/envs/test/lib/python3.8/site-packages/scipy/sparse/../../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/share/miniconda/envs/test/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)